---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Airmail.app
    - /Applications/Atom.app
    - /Applications/Dash.app
    folders:
    - path: ~/
      sort: datemodified
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: Dennis Roethig
    git_user_email: roethig.dennis@gmail.com
  - role: legit
  - role: hub
  - role: brew_package
    package_name: vim
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
  - role: cask_package
    package_name: java
  - role: brew_package
    package_name: android-sdk
  ## databases
  - role: brew_package
    package_name: postgres
  - role: brew_package
    package_name: mongodb
  ## deployment
  - role: brew_package
    package_name: heroku-toolbelt
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
    package_name: atom
